### ISSUE TITLE
Font-size and chatbox

### ISSUE THREAD

**Issue by FlashHit** [FlashHit/BetterIngameChat#17]
For lower resolutions the font becomes really small. And for high resolution the chatbox becomes really big compared to the rest of the ui.

So I would use a bigger font-size for 1280x720 and all lower resolutions. 
Then no scaling till 1920x1080.
And for every higher resolution its scaling again.

Also the chatbox height could be lower. atm it shows 8 messages at a time. I think 5-6 is enough.

So this would be like the vanilla chat size, just that it scales for resolutions above 1920x1080 again.

https://prnt.sc/wm6lmx 1920x1080
https://prnt.sc/wm6ly5 1600x900
https://prnt.sc/wm6mak 1280x720
https://prnt.sc/wm6mov 800x600

**Comment by kaloczikvn** [comment]
Fixed in 088a7b78141718666ada6232d9272f5198eef1e9
